(function () {
  const courses = [
    {
      id: "property",
      name: "Property I",
      code: "LAW 506",
      section: "4",
      professor: "Emeka Duruigbo",
      room: "LSB 208",
      days: [1, 3, 5],
      time: "9:00 AM",
      endTime: "9:50 AM",
      color: "#74a963",
      syllabusUrl: "syllabi/property-i-fall-2026.pdf",
      description: "Property rights, estates, future interests, ownership, and personal property.",
      standingNote: "Before each class, submit a one-page case brief for one case from that day's assigned reading to propertycasebriefs@gmail.com. No brief is required when the reading contains no case.",
    },
    {
      id: "contracts",
      name: "Contracts I",
      code: "LAW 504",
      section: "4",
      professor: "Jide James-Eluyode",
      email: "jide.jameseluyode@tsu.edu",
      phone: "708-646-8567",
      officeLocation: "Room 221J",
      officeHours: "In person: Monday/Wednesday 10:00-10:30 AM and 2:00-3:15 PM; Friday 10:00-10:30 AM and 12:00-1:00 PM (Friday requires a prior appointment). Virtual and other times by appointment.",
      room: "Room 206",
      days: [1, 3, 5],
      time: "11:00 AM",
      endTime: "11:50 AM",
      color: "#9255cb",
      syllabusUrl: "syllabi/contracts-i-fall-2026.pdf",
      description: "Contract formation and interpretation, reliance and restitution, the Statute of Frauds, parol evidence, good faith, and warranties.",
      standingNote: "Prepare every assigned reading, case, rule, problem, and in-class activity before class. The syllabus may be revised; monitor professor and law-school announcements.",
      requiredMaterials: [
        "Knapp, Crystal, Prince, Hart & Silverstein, Problems in Contract Law: Cases and Materials, 10th ed. (2023) - abbreviated KCP.",
        "Knapp, Crystal, Prince & Rowley, Rules of Contract Law (Aspen 2019 or later edition) - abbreviated RULES.",
        "Supplementary materials may be provided as needed.",
      ],
      grading: [
        "Quiz 1 - 50 points",
        "Quiz 2 - 50 points",
        "Midterm essay exam - 100 points",
        "Attendance, participation, and learning activities - 100 points",
        "Professor's end-of-semester exam - 200 points",
        "The items above total 500 points and make up 50% of the course grade.",
        "Law-school comprehensive final exam - 50% of the course grade; the law school supplies the final letter grade.",
      ],
      rules: [
        "Unaccommodated absences reduce course points; three or more may disqualify a student from taking the final exams.",
        "Entry is not permitted eight minutes after class discussion begins; late arrival counts as a missed class.",
        "Late assignments are not accepted unless the professor is notified before the deadline and grants permission.",
        "All submitted work must be the student's own and all sources must be acknowledged.",
        "Students are responsible for checking changes to the comprehensive exam's date, time, and room.",
      ],
    },
    {
      id: "legal-analysis",
      name: "Legal Analysis",
      code: "Course No. 7310",
      section: "1",
      professor: "Jenifer Points",
      email: "jenifer.points@tmslaw.tsu.edu",
      phone: "713-313-7276",
      officeLocation: "Room 231E",
      officeHours: "Mondays and Wednesdays, 1:00-3:00 PM; other times by appointment in person or through Zoom.",
      room: "Room 107",
      days: [1, 3, 5],
      time: "12:00 PM",
      endTime: "12:50 PM",
      color: "#d99b43",
      syllabusUrl: "syllabi/legal-analysis-fall-2026.pdf",
      description: "Critical reading, rule development, legal analysis, and predictive memorandum skills.",
      standingNote: "Canvas is used for course materials, grades, email, and submissions. Most assignments receive no credit if late; save every Canvas confirmation email.",
      alert: "NO GENERATIVE AI: Professor Points prohibits ChatGPT and every tool that generates, writes, or rewrites text for this course. Kita's Docket may track dates and requirements only; do not use it to create or complete Legal Analysis coursework.",
      aiRestricted: true,
      requiredMaterials: [
        "Coughlin, Malmud & Patrick, A Lawyer Writes, 4th ed.",
        "Brett A. Brosseit et al., Applied Critical Thinking & Analysis",
        "Romantz & Vinson, Legal Analysis, 4th ed.",
        "Digital Course Reader (320 pages)",
        "Core Grammar for Lawyers online program",
      ],
      grading: [
        "Daily exercises and other assignments - 100 points (10%)",
        "Exam 1 - 100 points (10%)",
        "Midterm Exam - 250 points (25%)",
        "Predictive Memorandum - 100 points (10%)",
        "Final Exam - 350 points (35% per grading table; a later policy paragraph says 30% - confirm)",
        "Core Grammar for Lawyers - 50 points (5%)",
        "Participation, Professionalism, and Attendance - 50 points (5%)",
      ],
      rules: [
        "Attendance is mandatory; only three absences are permitted.",
        "Most assignments must be uploaded to Canvas; no credit is given for late work.",
        "Use Word unless told otherwise; 14-point professional font, one-inch margins, double-spaced text, and bottom-centered page numbers.",
        "Remove identifying metadata and use an anonymous exam number when instructed.",
        "Collaboration is allowed only when Professor Points expressly permits it; final written work must be Rekita's own.",
      ],
    },
    {
      id: "torts",
      name: "Torts I",
      code: "LAW 508",
      section: "4",
      professor: "L. Darnell Weeden",
      email: "Larry.Weeden@tmslaw.tsu.edu",
      phone: "713-313-4249",
      officeLocation: "TMSL 236L",
      officeHours: "As printed: Mon./Tue./Wed./Fri. 9:00-9:50 AM; Mon./Wed./Fri. 11:00 AM-12:50 PM and 2:00-2:10 PM.",
      room: "Room 206",
      days: [1, 3, 5],
      time: "1:00 PM",
      endTime: "1:50 PM",
      color: "#5597c3",
      syllabusUrl: "syllabi/torts-i-fall-2026.pdf",
      description: "Intentional torts, privileges, negligence, causation, multiple tortfeasors, duty of care, and landowner liability.",
      standingNote: "Join the course TWEN page and monitor it for materials and announcements. Read assigned materials before discussion, including notes following cases.",
      requiredMaterials: [
        "Prosser, Wade & Schwartz's Torts, Cases and Materials, 15th ed. (2024)",
        "ISBN 9798887865522",
        "Highly recommended: Statsky & Wernet, Case Analysis and Fundamentals of Legal Writing (any edition)",
      ],
      grading: [
        "Exam #1 - 12.5%",
        "Midterm Exam (Exam #2) - 25%",
        "Exam #3 - 12.5%",
        "TMSL Final Uniform/Comprehensive Examination - 50%",
      ],
      rules: [
        "Five absences are permitted; excess absences may lower the grade or cause administrative withdrawal.",
        "All three course exams and the final uniform examination are mandatory.",
        "Class participation is expected but earns no points; some cases may be assigned to individual students.",
        "Devices may be used only for the e-textbook, notes, and class-related reference; mute phones and smart watches.",
      ],
    },
    {
      id: "civil-procedure",
      name: "Civil Procedure I",
      code: "Course 510",
      section: "4",
      professor: "Ana M. Otero",
      room: "Room 208",
      days: [1, 3, 5],
      time: "3:00 PM",
      endTime: "3:50 PM",
      color: "#da557d",
      syllabusUrl: "syllabi/civil-procedure-i-fall-2026.pdf",
      description: "Pleadings, joinder, federal jurisdiction, personal jurisdiction, and venue.",
      standingNote: "Assigned cases will be allocated to specific students before class. Monitor Canvas, TWEN, and email for quizzes, exercises, and assignment windows announced during the semester.",
    },
  ];

  const propertyRows = [
    ["2026-08-17", "class", "Welcome; Introduction to Property Law", "No textbook pages listed."],
    ["2026-08-19", "reading", "What is Property? Right to Transfer; Discovery and Conquest", "Read pp. 24-46 before class."],
    ["2026-08-21", "reading", "Right to Exclude; Trespass", "Read pp. 46-63 before class."],
    ["2026-08-24", "reading", "Right to Use", "Read pp. 63-76 before class."],
    ["2026-08-26", "reading", "Nuisance", "Read pp. 63-76 and 741-756 before class. The source table has duplicated/blank cells around this entry; verify against any revised schedule.", true],
    ["2026-08-28", "reading", "Right to Destroy", "Read pp. 76-88 before class."],
    ["2026-08-31", "exercise", "Nuisance Hypotheticals", "No textbook pages listed."],
    ["2026-09-02", "reading", "Ownership of Real Property; Adverse Possession", "Read pp. 89-107 before class."],
    ["2026-09-04", "reading", "Adverse Possession", "Read pp. 107-126 before class."],
    ["2026-09-07", "no-class", "Labor Day - no class", "University holiday."],
    ["2026-09-09", "reading", "Airspace Rights; Subsurface Rights", "Read pp. 127-141 before class."],
    ["2026-09-11", "reading", "Estates and Future Interests; Fee Simple Absolute", "Read pp. 295-305 before class."],
    ["2026-09-14", "exercise", "Adverse Possession Hypotheticals", "No textbook pages listed."],
    ["2026-09-16", "reading", "Life Estate", "Read pp. 305-316 before class."],
    ["2026-09-18", "reading", "Life Estate 2", "Read pp. 305-316 before class."],
    ["2026-09-21", "exercise", "Present Estates Hypotheticals", "No textbook pages listed."],
    ["2026-09-23", "reading", "Fee Simple Defeasible", "Read pp. 319-321: Fee Simple Determinable and Fee Simple Subject to a Condition Subsequent."],
    ["2026-09-25", "reading", "Executory Limitation and Other Defeasible-Fee Issues", "Read pp. 321-333 before class."],
    ["2026-09-28", "exercise", "Fee Simple Defeasible Hypotheticals", "No textbook pages listed."],
    ["2026-09-30", "review", "Midterm Review", "No textbook pages listed."],
    ["2026-10-02", "review", "Midterm Review 2", "No textbook pages listed."],
    ["2026-10-08", "exam", "Property Midterm Examination", "9:00-11:00 AM · LSB 203"],
    ["2026-10-12", "reading", "Modern Future Interests", "Read pp. 333-337: interests retained by the transferor."],
    ["2026-10-14", "reading", "Future Interests Created in a Transferee; Remainders", "Read pp. 337-341 before class."],
    ["2026-10-16", "reading", "Remainders", "Read pp. 337-341 before class."],
    ["2026-10-19", "reading", "Executory Interests", "Read pp. 342-344 before class."],
    ["2026-10-21", "reading", "Rule Against Perpetuities", "Read pp. 350-361 before class."],
    ["2026-10-23", "reading", "Concurrent Ownership and Marital Property", "Read pp. 363-369 before class."],
    ["2026-10-26", "exercise", "Future Interests Hypotheticals", "No textbook pages listed."],
    ["2026-10-28", "reading", "Severance; Partition", "Read pp. 369-382 before class."],
    ["2026-10-30", "reading", "Cotenant Rights and Duties", "Read pp. 382-386 before class."],
    ["2026-11-02", "reading", "Marital Property; Defining Marital Property", "Read pp. 387-404 before class."],
    ["2026-11-04", "reading", "Unmarried Couples; Same-Sex Marriage", "Read pp. 404-417 before class."],
    ["2026-11-06", "reading", "Water Law", "Read pp. 142-151 before class."],
    ["2026-11-09", "exercise", "Concurrent Ownership Hypotheticals", "No textbook pages listed."],
    ["2026-11-11", "reading", "Owning Personal Property; Rule of Capture", "Read pp. 153-165 before class."],
    ["2026-11-13", "reading", "Finders", "Read pp. 165-184 before class."],
    ["2026-11-16", "reading", "Adverse Possession of Chattels", "Read pp. 185-197 before class."],
    ["2026-11-18", "reading", "Gifts", "Read pp. 197-215 before class."],
    ["2026-11-20", "review", "Final Exam Review", "No textbook pages listed."],
    ["2026-11-23", "exam", "Property Final Examination", "Course-specific date conflicts with the university final-examination period beginning Nov. 30. Confirm if the professor updates it.", true],
    ["2026-11-24", "administrative", "Last day of classes", "Fall 2026 academic calendar."],
    ["2026-11-30", "administrative", "University final-examination period begins", "Runs through Dec. 10; conflicts with the Property final listed Nov. 23.", true],
    ["2026-08-19", "administrative", "Last day to add/drop", "Fall 2026 academic calendar."],
    ["2026-11-06", "administrative", "Last day to drop a class or withdraw", "Fall 2026 academic calendar."],
  ];

  const contractsRows = [
    ["2026-08-17", "reading", "Contracts, course expectations, and governing law", "Read KCP pp. 1-8 (top); RULES: Restatement (Second) §§ 1 and 3; UCC §§ 1-103, 2-102, and 2-105(1). Brief R.R. v. M.H. & Another."],
    ["2026-08-19", "reading", "Sources of contract law and contract theory", "Read KCP pp. 8-22; RULES Restatement editor's note pp. 1-3 (top) and § 17; CISG editor's note pp. 355-357 and Articles 1, 2, and 10."],
    ["2026-08-21", "reading", "Mutual assent and objective theory", "Read KCP pp. 23-33 (top); RULES Restatement §§ 18-23. Note Lucy v. Zehmer and Ray v. William G. Eurice & Bros.; brief Meyer v. Uber Technologies."],
    ["2026-08-24", "reading", "Offer and acceptance - overarching rules of offer", "Review RULES Restatement §§ 17, 22, 24, 25, 40, 50(1), 60, 63(a), 36(1), 38, 39, 43, and 59. Brief Ray v. Eurice; Leonard v. PepsiCo; Carlill v. Carbolic Smoke Ball; Lonergan v. Scolnick; and Nebraska Seed Co. v. Harsh."],
    ["2026-08-26", "reading", "Termination of an offer", "Read KCP pp. 34-49 and Problem 2-1; review the listed Restatement offer rules; note Dickinson v. Dodds and Normile v. Miller."],
    ["2026-08-28", "reading", "Bilateral and unilateral contracts - Part 1", "Read KCP pp. 49-67 (top) and Problem 2-2; RULES Restatement §§ 22, 24-25, 45, and 50. Note Cook v. Coldwell Banker/Frank Laiben Realty and Sateriale v. R.J. Reynolds Tobacco."],
    ["2026-08-31", "reading", "Bilateral and unilateral contracts - Part 2", "Continue KCP pp. 49-67 (top), Problem 2-2, and Restatement §§ 22, 24-25, 45, and 50; revisit Cook and Sateriale."],
    ["2026-09-02", "reading", "Acceptance, mirror-image rule, mailbox rule, and acceptance by conduct", "Review UCC §§ 2-204 and 2-206; Restatement §§ 22, 50(1), 63, and 69; revisit KCP pp. 34-49. Brief Austin v. Burge, Brogden v. Metropolitan Railway, Laredo National Bank v. Gordon, and Adams v. Lindsell."],
    ["2026-09-04", "reading", "Mailbox rule and agreements to agree", "Read KCP pp. 66-87. Note Walker v. Keith, Quake Construction v. American Airlines, and Problem 2-3."],
    ["2026-09-07", "no-class", "Labor Day - no class", "University holiday."],
    ["2026-09-09", "reading", "Consideration I - meaning, nature, and scope", "Read KCP pp. 87-102. Note Hamer v. Sidway, Pennsy Supply v. American Ash Recycling, and Restatement §§ 71 and 79."],
    ["2026-09-11", "reading", "Consideration II - past consideration and moral agreements", "Read KCP pp. 102-116 (top). Note Dougherty v. Salt and Plowman v. Indian Refining."],
    ["2026-09-14", "reading", "Consideration III - sufficiency and adequacy", "Read KCP pp. 116-133 (top). Brief Schnell v. Nell; note Harris v. Time, Batsakis v. Demotsis, Marshall Durbin Food v. Baker, and Problem 2-6."],
    ["2026-09-16", "reading", "Mutual assent and the UCC", "Read KCP pp. 133-147. Note Jannusch v. Naffziger and E.C. Styberg Engineering v. Eaton; review the listed UCC, Restatement, and CISG provisions."],
    ["2026-09-18", "reading", "Qualified acceptance and battle of the forms", "Read KCP p. 147 (bottom)-168. Note Princess Cruises v. General Electric and Brown Machine v. Hercules; RULES Restatement § 59 and UCC § 2-207."],
    ["2026-09-21", "reading", "Battle of the forms continued", "Read KCP pp. 168-181. Note Paul Gottlieb & Co. v. Alps South, Problems 2-7 and 2-8, Restatement § 59, and UCC § 2-207."],
    ["2026-09-23", "reading", "Electronic and layered contracting", "Read KCP pp. 181-212. Note DeFontes v. Dell and Long v. Provide Commerce; browse Hill v. Gateway and Klocek v. Gateway; note Nguyen v. Barnes & Noble, Problem 2-9, and the Chapter 2 review questions."],
    ["2026-09-25", "quiz", "Contracts Quiz 1", "Multiple-choice quiz worth 50 points."],
    ["2026-09-28", "reading", "Promissory estoppel and promisee reliance", "Read KCP pp. 212-224. Note Kirksey v. Kirksey, Harvey v. Dow, and Restatement § 90(1)."],
    ["2026-09-30", "reading", "Promissory estoppel and charitable subscriptions", "Read KCP pp. 224-235. Note King v. Trustees of Boston University, Maryland National Bank v. United Jewish Appeal Federation, Restatement § 90(2), and Problem 3-1."],
    ["2026-10-02", "reading", "Promissory estoppel in a commercial context", "Read KCP pp. 235-253. Note Katz v. Danny Dare, Romano v. Site Acquisitions, and Aceves v. U.S. Bank."],
    ["2026-10-05", "exam", "Contracts Midterm Exam", "9:00-11:00 AM - Room 208. Essay exam worth 100 points; no regular classes during midterm week."],
    ["2026-10-12", "reading", "Irrevocable offers, option contracts, firm offers, and reliance", "Read KCP pp. 253-265. Note Berryman v. Kmoch and James Baird v. Gimbel Bros.; review Restatement §§ 87 and 63 and listed UCC provisions."],
    ["2026-10-14", "reading", "Reasonable reliance on an unaccepted offer", "Read KCP pp. 265-281. Note Drennan v. Star Paving and Pop's Cones v. Resorts International."],
    ["2026-10-16", "reading", "Restitution in the absence of a promise", "Read KCP pp. 286-316. Note Credit Bureau Enterprises v. Pelo, Commerce Partnership v. Equity Contracting, Watts v. Watts, and Marvin v. Marvin; review Restatement §§ 82, 83, and 86."],
    ["2026-10-19", "reading", "Promissory restitution", "Read KCP pp. 316-334. Note Mills v. Wyman, Webb v. McGowin, and Problems 3-5 and 3-6."],
    ["2026-10-21", "reading", "Statute of Frauds - scope and application", "Read KCP pp. 335-347 (top). Note Crabtree v. Elizabeth Arden Sales and Freedman v. Chemical Construction."],
    ["2026-10-23", "reading", "Statute of Frauds - writing, part performance, and reliance", "Read KCP pp. 347-372. Note Beaver v. Brumlow, Alaska Democratic Party v. Rice, Klinke v. Famous Recipe Fried Chicken, Problems 4-1 and 4-2, and Restatement §§ 129 and 139."],
    ["2026-10-26", "reading", "Statute of Frauds and sale of goods", "Read KCP pp. 372-386. Note Buffaloe v. Hart, Sedmak v. Charlie's Chevrolet, the listed UCC provisions, and Problem 4-4."],
    ["2026-10-28", "reading", "Express terms and principles of interpretation", "Read KCP pp. 387-418 (top). Note Prochazka v. Bee Development and Frigaliment Importing v. B.N.S.; review the listed Restatement and UCC provisions."],
    ["2026-10-30", "reading", "Reasonable expectations doctrine", "Read KCP pp. 418-429. Note C & J Fertilizer v. Allied Mutual and Problem 5-1."],
    ["2026-11-02", "reading", "Parol evidence rule - common law", "Read KCP pp. 429-440. Note Thompson v. Libby and Restatement §§ 209-211 and 213-217."],
    ["2026-11-04", "reading", "Parol evidence rule - UCC", "Read KCP pp. 440-454. Note Taylor v. State Farm and UCC § 1-303(d)-(e). The syllabus says this class may be remote.", true],
    ["2026-11-06", "quiz", "Contracts Quiz 2", "Multiple-choice quiz worth 50 points."],
    ["2026-11-09", "reading", "Parol evidence - fraud, mistake, and trade usage", "Read KCP pp. 454-481. Note Sherrodd v. Morrison-Knudsen and Nanakuli Paving v. Shell Oil; review UCC §§ 2-202 and 1-303; brief Hurst v. W.J. Lake."],
    ["2026-11-11", "reading", "Supplementing the agreement - implied terms", "Read KCP pp. 485-496. Note Wood v. Lucy, Lady Duff-Gordon and Leibel v. Raynor Manufacturing; review UCC §§ 2-306(2), 2-308, and 2-309."],
    ["2026-11-13", "reading", "Implied obligation of good faith", "Read KCP pp. 496-512. Note Seidenberg v. Summit Bank and the listed Restatement and UCC provisions."],
    ["2026-11-16", "reading", "Good faith - satisfaction and discretion", "Read KCP pp. 512-529. Note Morin Building Products v. Baystone Construction and Locke v. Warner Bros."],
    ["2026-11-18", "reading", "Good faith continued", "Read KCP pp. 529-550. Note Geysen v. Securitas Security Services and Problem 6-2."],
    ["2026-11-20", "reading", "Warranties", "Read KCP pp. 550-571. Note Bayliner Marine v. Crow and Speight v. Walters Development; review UCC §§ 2-313, 2-314, 2-315, and 2-316 and Problem 6-4."],
    ["2026-11-23", "exam", "Professor's Contracts Final Exam - tentative", "The schedule places this under Nov. 23, 2026 at 11:00 AM in Room 206, but the line itself repeats a stale 'Nov. 24, 2025' date. Confirm the actual date, time, and room. Worth 200 points.", true],
    ["2026-11-30", "exam", "Contracts Comprehensive Final Exam - exact date TBD", "The law-school multiple-choice comprehensive final will occur during Nov. 30-Dec. 10 and counts for 50% of the course grade. Exact date, time, and room remain TBD.", true, "2026-12-10"],
  ];

  const legalAnalysisRows = [
    ["2026-08-17", "reading", "Week 1 - Introduction; Sources and Systems of Law", "A Lawyer Writes pp. 15-31; Legal Analysis pp. 3-19; ACTLA pp. 3-23; Course Reader pp. 3-10, 36-58, 98-110, 250-264. Topics include jurisdiction, precedent, authority, case structure, and litigation.", false, "2026-08-21"],
    ["2026-08-24", "assignment", "Eilers v. Coy case brief due", "Post on Canvas before class starts. Brief Eilers v. Coy, 582 F. Supp. 1093 (D. Minn. 1984), using Course Reader pp. 80-82 and briefing guidance at pp. 13-17."],
    ["2026-08-24", "reading", "Week 2 - Critical Reading and Case Briefing", "A Lawyer Writes pp. 33-64; Course Reader pp. 16-18, 59-78; ACTLA pp. 27-58. Includes issue statements and broad versus narrow issues.", false, "2026-08-28"],
    ["2026-08-31", "assignment", "First three attractive-nuisance case briefs due", "Post on Canvas before class starts. Complete briefs for the first three cases in the Attractive Nuisance Memorandum assignment case pool."],
    ["2026-08-31", "reading", "Week 3 - Explicit and Implicit Rules", "Legal Analysis pp. 21-29, 31-34; A Lawyer Writes pp. 65-78, 105-114; ACTLA pp. 59-67, 127-133, 152-167; Course Reader pp. 80-93. The syllabus says the ACTLA cases do not need briefs.", false, "2026-09-04"],
    ["2026-09-09", "assignment", "Implicit-rules homework due", "Post on Canvas before class starts and bring a printed copy. From ACTLA pp. 152-156, write every implicit rule identified from the courts' holdings."],
    ["2026-09-09", "reading", "Week 4 - Rule Synthesis and Inductive Reasoning", "ACTLA pp. 133-135, 193-212; Legal Analysis pp. 30-31, 47-50; Course Reader pp. 23-34, 237-240. Monday is a holiday, so class meets Wednesday and Friday.", false, "2026-09-11"],
    ["2026-09-14", "reading", "Week 5 - Clear Rule Statements and Rule Explanation", "A Lawyer Writes pp. 115-118; ACTLA pp. 67-78. Exam #1 is Friday.", false, "2026-09-18"],
    ["2026-09-18", "exam", "Legal Analysis Exam #1", "Multiple-choice and short-answer exam covering case reading, rule types, explicit and implicit rules, synthesis, rule ordering, court structure, judicial opinions, and case briefing."],
    ["2026-09-21", "reading", "Week 6 - Deductive Analysis; CRAC/CREAC/IRAC", "A Lawyer Writes pp. 99-103; Legal Analysis pp. 67-84; ACTLA pp. 96-122, 139-150; Course Reader pp. 151-185. Includes essay-exam writing skills.", false, "2026-09-25"],
    ["2026-09-28", "assignment", "Bubbles practice essay due", "Post the completed practice-exam essay on Canvas by 9:00 AM."],
    ["2026-09-28", "reading", "Week 7 - Live Drafting and Memorandum Basics", "Legal Analysis pp. 119-144; Attractive Nuisance Memorandum Assignment on Canvas; A Lawyer Writes pp. 3-9; Course Reader pp. 282-298. Includes live review and CREAC discussion-section basics.", false, "2026-10-02"],
    ["2026-10-05", "no-class", "Legal Analysis midterm week - no class", "No regular class during midterm week.", false, "2026-10-09"],
    ["2026-10-07", "exam", "Legal Analysis Midterm Exam", "9:00 AM - Room 202. NextGen integrated-set format."],
    ["2026-10-12", "assignment", "Attractive-nuisance case briefs due", "Post on Canvas before class starts. Brief Lopez-Perez v. BNSF Railway Co., Renaud v. Black, and Craig v. Bailey Bros. Realty, Inc. using only the edited cases on Canvas and the UDW approach."],
    ["2026-10-12", "reading", "Week 9 - CREAC Application; Counterargument and Rebuttal", "A Lawyer Writes pp. 155-161, 181-195; ACTLA pp. 79-94, 169-176. Includes review of the Micki Mouse CREAC.", false, "2026-10-16"],
    ["2026-10-16", "assignment", "Micki Mouse CREAC due", "Post on Canvas by 9:00 AM."],
    ["2026-10-19", "reading", "Week 10 - Completing and Polishing the Memorandum", "A Lawyer Writes pp. 141-154, 251-283, 286-292 through section b, and pp. 295-309 starting at section B; Course Reader pp. 301-322. Covers remaining memo parts, citation, editing, and polishing.", false, "2026-10-23"],
    ["2026-10-25", "assignment", "Attractive Nuisance Memorandum due", "Submit on Canvas by 11:59 PM using an anonymous exam number. Bring a printed copy showing only the exam number to Monday's class."],
    ["2026-10-26", "reading", "Week 11 - Rule Synthesis and Statutory Interpretation", "More Rule Synthesis reading is TBD. Also read Legal Analysis pp. 85-99; A Lawyer Writes pp. 215-231; Course Reader pp. 111-131, 224-236, 243-249, 260-266. Bring a printed memorandum.", true, "2026-10-30"],
    ["2026-11-02", "reading", "Week 12 - Analogical Reasoning", "A Lawyer Writes pp. 163-164; Legal Analysis pp. 39-65; ACTLA pp. 135-137; Course Reader pp. 94-96, 132-140, 267-269; People v. Barney, 742 N.Y.S.2d 451, via Lexis or Westlaw.", false, "2026-11-06"],
    ["2026-11-08", "assignment", "Core Grammar for Lawyers due", "Complete all 24 lessons and earn at least 75% on the post-test by 11:59 PM. Worth 50 points; late work or a score below 75 earns zero. A 95+ post-test score earns 10 extra-credit points."],
    ["2026-11-09", "reading", "Week 13 - Policy-Based Reasoning and Bases for Rules", "ACTLA pp. 187-188; Legal Analysis pp. 101-117; A Lawyer Writes pp. 207-214; Course Reader pp. 195-213.", false, "2026-11-13"],
    ["2026-11-16", "reading", "Week 14 - Review of Rules and Legal Analysis", "Course Reader pp. 214-223; final-exam review.", false, "2026-11-20"],
    ["2026-11-23", "review", "Week 15 - Final Exam Review", "Reading is TBD. Final exam date remains TBD.", true],
  ];

  const tortsRows = [
    ["2026-08-17", "reading", "Week 1 - Introduction, Fault, Procedure, Intent, and Battery", "Read pp. 1-53.", false, "2026-08-21"],
    ["2026-08-24", "reading", "Week 2 - Intentional Interference with Person or Property", "Read pp. 53-107: battery, assault, false imprisonment, intentional infliction of emotional distress, trespass to land, and trespass to chattels.", false, "2026-08-28"],
    ["2026-08-31", "reading", "Week 3 - Conversion, Participation Liability, Privileges, and Consent", "Read pp. 107-157.", false, "2026-09-04"],
    ["2026-09-07", "reading", "Week 4 - Privileges and Defenses", "Read pp. 157-192: consent, self-defense, defense and recovery of property, shopkeeper's privilege, necessity, authority of law, and discipline. No class Monday for Labor Day.", false, "2026-09-11"],
    ["2026-09-14", "reading", "Week 5 - Negligence, Breach, and the Reasonable Person", "Read pp. 193-227. Exam #1 is Friday.", false, "2026-09-18"],
    ["2026-09-18", "exam", "Torts Exam #1", "12.5% of final grade. Includes 25 objective multiple-choice questions and a five-point timed essay."],
    ["2026-09-21", "reading", "Week 6 - Professional Standard and Aggravated Negligence", "Read pp. 227-277: reasonable person, professional standard, urgent care, gross negligence, recklessness, and who decides rules of conduct.", false, "2026-09-25"],
    ["2026-09-28", "reading", "Week 7 - Rules of Conduct and Statutory Violations", "Read pp. 277-330: judge versus jury and violation of statute as proof of negligence.", false, "2026-10-02"],
    ["2026-10-05", "review", "Week 8 - Torts midterm week", "Midterm exam week runs Monday through Friday.", false, "2026-10-09"],
    ["2026-10-09", "exam", "Torts Midterm Exam (Exam #2)", "9:00-11:00 AM - Room 202. Counts for 25% and consists of 60 objective multiple-choice questions."],
    ["2026-10-12", "reading", "Week 9 - Proof of Negligence and Causation in Fact", "Read pp. 330-384: but-for test, reasonable inference, concurrent and overdetermined causes, substantial factor, loss of chance, toxic torts, and epidemiologic evidence.", false, "2026-10-16"],
    ["2026-10-19", "reading", "Week 10 - Causation and Scope of Liability", "Read pp. 384-433: toxic tort evidence, proximate/legal cause, direct versus remote causes, foreseeability, increased risk, and proportionality.", false, "2026-10-23"],
    ["2026-10-26", "reading", "Week 11 - Intervening Causes and Multiple Tortfeasors", "Read pp. 434-489: scope of liability, intervening causes, joinder, satisfaction and release, contribution, and indemnity.", false, "2026-10-30"],
    ["2026-11-02", "reading", "Week 12 - Apportionment and Duty of Care", "Read pp. 489-540: multiple tortfeasors, contribution and indemnity, apportionment, privity, tort versus contract, foreseeability limits, policy-based no-duty rules, and failure to act.", false, "2026-11-06"],
    ["2026-11-09", "reading", "Week 13 - Failure to Act, Economic Loss, and Emotional Distress", "Read pp. 540-598.", false, "2026-11-13"],
    ["2026-11-16", "reading", "Week 14 - Emotional Distress and Landowner Liability", "Read pp. 598-668: unborn children, owners and occupiers of land, and injuries on and outside the premises.", false, "2026-11-20"],
    ["2026-11-23", "exam", "Torts Exam #3", "12.5% of final grade. Consists of 30 objective multiple-choice questions."],
  ];

  const civilRows = [
    ["2026-08-14", "preparation", "Complete Civil Procedure pre-start review", "Before Aug. 17: watch the American Court System and Civil Litigation videos; read Orin Kerr's “How to Read a Legal Opinion”; complete Review Exercise #1. The syllabus labels this work “Pre-Start (August 10-14).”"],
    ["2026-08-17", "reading", "Introduction to Pleading", "For Aug. 17 and 19: review Exercise #1 and Chapters 1-2; review Chapter 13, pp. 405-452; review Exercise #2; prepare Ashcroft v. Iqbal (p. 430) and Swanson v. Citibank (p. 441). Exact division between the two class dates is not specified.", true, "2026-08-19"],
    ["2026-08-21", "reading", "Responding to the Complaint", "Chapter 14, pp. 453-465; answer Exercise #3 using the applicable rules; prepare Virgin Records America v. Lacey (p. 455)."],
    ["2026-08-24", "reading", "Pleading, continued", "For Aug. 24 and 26: Chapter 14, pp. 465-489; prepare Matos v. Nextran, Inc. (p. 465), Hunter v. Serv-Tech, Inc. (p. 475), and Reis Robotics USA, Inc. v. Concept Industries, Inc. (p. 483). Exact division between dates is not specified.", true, "2026-08-26"],
    ["2026-08-28", "reading", "Complete Chapter 14 reading", "Chapter 14, pp. 490-497; prepare Ingraham v. United States (listed at p. 489)."],
    ["2026-08-31", "exercise", "Complete Chapter 14 and Exercise #4", "Review the applicable rules and prepare answers before discussing the assigned Chapter 15 cases."],
    ["2026-09-02", "reading", "Care and Candor in Pleading", "For Sept. 2 and 4: Chapter 15, pp. 499-523; prepare Hays v. Sony Corp. of America (p. 501) and Hunter v. Earthgrains Co. Bakery (printed as p. 5112, likely a page-number typo).", true, "2026-09-04"],
    ["2026-09-07", "no-class", "Labor Day - no class", "University holiday."],
    ["2026-09-09", "reading", "Amending Pleadings", "Chapter 16, pp. 525-539; complete Exercise #5 questions on Rule 15; prepare Beeck v. Aquaslide ‘N’ Dive Corp. (p. 531)."],
    ["2026-09-11", "reading", "Joinder of Claims and Parties", "Review the Joinder of Parties PPT and Constitutional Requirement of Notice and Methods of Service PPT; prepare Mullane v. Central Hanover Bank (p. 320)."],
    ["2026-09-14", "reading", "Diversity Jurisdiction", "For Sept. 14 and 16: review the Diversity Jurisdiction PPT; begin Chapter 3, pp. 43-92; prepare Gordon v. Steele (p. 46) and Mas v. Perry (p. 56). Exact division between dates is not specified.", true, "2026-09-16"],
    ["2026-09-18", "reading", "Diversity Jurisdiction cases", "Prepare Hertz Corp. v. Friend (p. 66) and Diefenthal v. C.A.B. (p. 77)."],
    ["2026-09-21", "reading", "Federal Question Jurisdiction", "For Sept. 21 and 23: review the Federal Question Jurisdiction PPT; begin Chapter 4, pp. 93-127; prepare Louisville & Nashville RR v. Mottley (p. 96) and Gunn v. Minton (p. 113). Exact division between dates is not specified.", true, "2026-09-23"],
    ["2026-09-25", "reading", "Removal of Cases to Federal Court", "Review the Removal PPT; Chapter 5, pp. 129-145; prepare Avitts v. Amoco (p. 131)."],
    ["2026-09-28", "reading", "Removal and Supplemental Jurisdiction", "For Sept. 28 and 30: finalize removal; review the Supplemental Jurisdiction PPT; Chapter 20, pp. 671-705; prepare United Mine Workers v. Gibbs (p. 673). Exact division between dates is not specified.", true, "2026-09-30"],
    ["2026-10-02", "reading", "Finalize Supplemental Jurisdiction", "Prepare Owen Equipment & Erection v. Kroger (p. 685) and finalize the supplemental-jurisdiction discussion."],
    ["2026-10-05", "review", "Civil Procedure midterm week begins", "Midterm week runs Oct. 5-9."],
    ["2026-10-06", "exam", "Civil Procedure Midterm Exam", "Closed book · multiple-choice and essay questions · 9:00-11:00 AM."],
    ["2026-10-12", "reading", "Introduction to Personal Jurisdiction", "For Oct. 12 and 14: overview of Personal Jurisdiction; Chapter 6, pp. 149-180. Exact division between dates is not specified.", true, "2026-10-14"],
    ["2026-10-16", "reading", "Personal Jurisdiction cases", "Prepare Pennoyer v. Neff (p. 152) and International Shoe v. State of Washington (p. 167)."],
    ["2026-10-19", "reading", "Specific In Personam Jurisdiction", "For Oct. 19, 21, and 23: Chapter 7, pp. 181-254; prepare World Wide Volkswagen v. Woodson, Burger King v. Rudzewicz, Asahi Metal Industry v. Superior Court, and Ford Motor Co. v. Montana Eighth Judicial District Court. Exact division between dates is not specified.", true, "2026-10-23"],
    ["2026-10-26", "reading", "Other Constitutional Bases for Personal Jurisdiction", "For Oct. 26, 28, and 30: Chapter 8, pp. 255-297; prepare Daimler AG v. Bauman (p. 259) and Burnham v. Superior Court (p. 279). Exact division between dates is not specified.", true, "2026-10-30"],
    ["2026-11-02", "reading", "Long Arm Statutes", "For Nov. 2 and 4: Chapter 9, pp. 299-315; prepare Bensusan Restaurant Corp. v. King (p. 307). Exact division between dates is not specified.", true, "2026-11-04"],
    ["2026-11-06", "exercise", "Personal-jurisdiction writing exercises", "Writing exercises on personal jurisdiction."],
    ["2026-11-09", "reading", "Venue", "For Nov. 9, 11, and 13: review the Venue PPT; Chapter 11, pp. 355-371; prepare Uffner v. La Reunion Francaise (p. 364). Exact division between dates is not specified.", true, "2026-11-13"],
    ["2026-11-16", "reading", "Challenges to Venue", "For Nov. 16, 18, and 20: Chapter 12, pp. 373-400; prepare MacMunn v. Eli Lilly Co. (p. 377) and Piper Aircraft Company v. Reyno (p. 385). Exact division between dates is not specified.", true, "2026-11-20"],
    ["2026-11-23", "exam", "Civil Procedure Final Exam", "Cumulative and closed book; may include a take-home essay component. Time is not listed. The course date precedes the university's general final-examination period, so preserve both dates.", true],
    ["2026-11-24", "administrative", "Last day of class", "Listed the day after the course final examination."],
    ["2026-11-30", "administrative", "University final-examination period begins", "Runs through Dec. 10; the Civil Procedure course final is listed separately on Nov. 23.", true],
  ];

  function rowsToItems(courseId, rows) {
    return rows.map(([date, type, title, details, flagged = false, endDate = ""], index) => ({
      id: `${courseId}-${String(index + 1).padStart(2, "0")}`,
      courseId,
      date,
      endDate,
      type,
      title,
      details,
      flagged,
      done: false,
    }));
  }

  const materials = [
    {
      id: "property-syllabus",
      courseId: "property",
      title: "Property I - Fall 2026 Syllabus",
      type: "Original syllabus PDF",
      addedDate: "2026-08-16",
      content: "LAW 506 Section 4 with Professor Emeka Duruigbo, including course policies, recurring case briefs, exams, and the complete reading schedule.",
      size: 575644,
      url: "syllabi/property-i-fall-2026.pdf",
    },
    {
      id: "contracts-syllabus",
      courseId: "contracts",
      title: "Contracts I - Fall 2026 Syllabus",
      type: "Original syllabus PDF",
      addedDate: "2026-08-16",
      content: "LAW 504 Section 4 with Professor Jide James-Eluyode, including course rules, grading, and the complete daily reading schedule.",
      size: 496706,
      url: "syllabi/contracts-i-fall-2026.pdf",
    },
    {
      id: "torts-syllabus",
      courseId: "torts",
      title: "Torts I - Fall 2026 Syllabus",
      type: "Original syllabus PDF",
      addedDate: "2026-08-16",
      content: "LAW 508 Section 4 with Professor L. Darnell Weeden.",
      size: 277457,
      url: "syllabi/torts-i-fall-2026.pdf",
    },
    {
      id: "legal-analysis-syllabus",
      courseId: "legal-analysis",
      title: "Legal Analysis - Fall 2026 Syllabus",
      type: "Original syllabus PDF",
      addedDate: "2026-08-16",
      content: "Course 7310 Section 1 with Professor Jenifer Points, including the daily schedule and course rules.",
      size: 668376,
      url: "syllabi/legal-analysis-fall-2026.pdf",
    },
    {
      id: "civil-procedure-syllabus",
      courseId: "civil-procedure",
      title: "Civil Procedure I - Fall 2026 Syllabus",
      type: "Original syllabus PDF",
      addedDate: "2026-08-16",
      content: "Course 510 Section 4 with Professor Ana M. Otero.",
      size: 673392,
      url: "syllabi/civil-procedure-i-fall-2026.pdf",
    },
    {
      id: "property-summary",
      courseId: "property",
      title: "Property - LAW 506 Sec. 4: Docket Notes and Items to Confirm",
      type: "Verified syllabus notes",
      addedDate: "2026-08-12",
      content: "Recurring case-brief requirement, final-exam conflict, undated Theories of Property and Fee Tail readings, and take-home work whose dates will be announced later.",
    },
    {
      id: "civil-procedure-summary",
      courseId: "civil-procedure",
      title: "Civil Procedure I - Course 510 Sec. 4: Verified Syllabus Notes",
      type: "Verified syllabus notes",
      addedDate: "2026-08-13",
      content: "Professor Ana M. Otero. Monday, Wednesday, and Friday, 3:00-3:50 PM in Room 208. Includes pre-start work, weekly readings, Oct. 6 midterm, Nov. 23 final, and standing reminders for TWEN quizzes, timed essays, and assigned-case notices.",
    },
    {
      id: "legal-analysis-summary",
      courseId: "legal-analysis",
      title: "Legal Analysis - Course No. 7310 Sec. 1: Verified Syllabus Notes",
      type: "Verified Fall 2026 syllabus",
      addedDate: "2026-08-16",
      content: "Professor Jenifer Points. M/W/F, 12:00-12:50 PM in Room 107. Includes required books, weekly readings, all dated Canvas work, exams, memorandum, Core Grammar, grading, three-absence limit, formatting rules, and the strict prohibition on generative AI.",
    },
    {
      id: "torts-summary",
      courseId: "torts",
      title: "Torts I - LAW 508 Sec. 4: Verified Syllabus Notes",
      type: "Verified Fall 2026 syllabus",
      addedDate: "2026-08-16",
      content: "Professor L. Darnell Weeden. M/W/F, 1:00-1:50 PM in Room 206. Includes the required 15th-edition casebook, TWEN reminder, complete weekly readings, three mandatory course exams, final exam TBD, grading weights, and five-absence limit.",
    },
  ];

  window.KITAS_DOCKET_SEED = {
    term: { name: "Fall 2026", startDate: "2026-08-17", endDate: "2026-11-24" },
    courses,
    items: [
      ...rowsToItems("property", propertyRows),
      ...rowsToItems("contracts", contractsRows),
      ...rowsToItems("legal-analysis", legalAnalysisRows),
      ...rowsToItems("torts", tortsRows),
      ...rowsToItems("civil-procedure", civilRows),
    ],
    materials,
    quickLinks: {
      firstTwoWeeksChecklist: "https://docs.google.com/document/d/1sDiEGBNyVgX1X1b9Nn8E2D76XiI0jrV-VU9ELwzWwXM/edit",
      oneNote: "",
    },
    standingFlags: [
      { id: "property-undated-theories", courseId: "property", title: "Theories of Property has no date", details: "Pages 1-24 appear without a clearly printed ‘Before This Date.’" },
      { id: "property-undated-fee-tail", courseId: "property", title: "Fee Tail has no date", details: "Pages 317-319 appear without a clearly printed ‘Before This Date.’" },
      { id: "property-comprehensive", courseId: "property", title: "Comprehensive Examination is TBA", details: "No date, time, or location is provided." },
      { id: "property-take-home", courseId: "property", title: "Property take-home work will be announced", details: "Several problems and hypotheticals are expected, but the syllabus gives no advance dates." },
      { id: "contracts-professor-final", courseId: "contracts", title: "Confirm the professor's Contracts final date", details: "The schedule places it under Nov. 23, 2026, but the event line repeats a stale Nov. 24, 2025 date. It also labels 11:00 AM and Room 206 as tentative." },
      { id: "contracts-comp-final", courseId: "contracts", title: "Contracts comprehensive final date is TBD", details: "The exam will occur during Nov. 30-Dec. 10, but the law school has not listed the exact date, time, or room." },
      { id: "contracts-remote-nov4", courseId: "contracts", title: "Nov. 4 Contracts class may be remote", details: "The syllabus says this class session may be conducted remotely; confirm before class." },
      { id: "civil-twen", courseId: "civil-procedure", title: "Mandatory TWEN quizzes will be announced", details: "Watch email for each quiz's open and close dates." },
      { id: "civil-essays", courseId: "civil-procedure", title: "Timed essay-exam dates are pending", details: "Multiple graded essays are planned; dates and point values will be announced." },
      { id: "civil-uniform", courseId: "civil-procedure", title: "Uniform Exam date is not listed", details: "The syllabus says it will be administered in December and counts for 50% of the final grade." },
      { id: "civil-cases", courseId: "civil-procedure", title: "Individual case assignments are pending", details: "The professor will assign cases to specific students before class and post a separate document with focus questions." },
      { id: "legal-ai-ban", courseId: "legal-analysis", title: "Generative AI is prohibited", details: "Do not use ChatGPT or any tool that generates, writes, or rewrites text for Legal Analysis. Use Kita's Docket only to track dates and course requirements." },
      { id: "legal-final-tbd", courseId: "legal-analysis", title: "Legal Analysis final exam date is TBD", details: "The syllabus provides the format and topics but no date, time, or room." },
      { id: "legal-final-weight-conflict", courseId: "legal-analysis", title: "Confirm Legal Analysis final-exam weight", details: "The grading table lists 350 of 1000 points (35%), while a later policy paragraph says 30%." },
      { id: "legal-week11-reading", courseId: "legal-analysis", title: "Week 11 More Rule Synthesis reading is TBD", details: "The syllabus lists the topic for Oct. 26-30 but leaves this reading as TBD." },
      { id: "legal-week15-reading", courseId: "legal-analysis", title: "Nov. 23 final-review reading is TBD", details: "The final-review topic is listed, but the assigned reading remains TBD." },
      { id: "legal-grammar-groups", courseId: "legal-analysis", title: "Confirm Rekita's grammar-presentation group", details: "Group dates: Sept. 9, 11, 21, 28, 30; Oct. 12, 14, 28; Nov. 2, 4, 11, 18. Add only Rekita's assigned date to her personal deadline list." },
      { id: "torts-final-tbd", courseId: "torts", title: "Torts final uniform examination is TBD", details: "TMSL Administration will announce the date during the Nov. 30-Dec. 10 final-exam period." },
      { id: "torts-office-hours", courseId: "torts", title: "Torts office-hours line should be confirmed", details: "The app preserves the unusually broad schedule exactly as printed in the syllabus." },
      { id: "torts-practice", courseId: "torts", title: "Additional Torts exams or reviews may be announced", details: "Monitor TWEN for separately scheduled reviews, practice exams, and other materials." },
    ],
  };
})();
