(function () {
  const courses = [
    {
      id: "property",
      name: "Property I",
      code: "LAW 506",
      section: "4",
      professor: "Emeka Duruigbo",
      room: "LSB 208",
      days: [1, 3, 5],
      time: "9:00 AM",
      endTime: "9:50 AM",
      color: "#74a963",
      description: "Property rights, estates, future interests, ownership, and personal property.",
      standingNote: "Before each class, submit a one-page case brief for one case from that day's assigned reading to propertycasebriefs@gmail.com. No brief is required when the reading contains no case.",
    },
    {
      id: "contracts",
      name: "Contracts I",
      code: "Course details pending",
      section: "",
      professor: "Not yet provided",
      room: "Not yet provided",
      days: [1, 3, 5],
      time: "11:00 AM",
      endTime: "",
      color: "#9255cb",
      description: "Syllabus and course details can be added when available.",
      standingNote: "Class schedule provided; syllabus details are still pending.",
    },
    {
      id: "legal-analysis",
      name: "Legal Analysis",
      code: "Course details pending",
      section: "",
      professor: "Not yet provided",
      room: "Not yet provided",
      days: [1, 3, 5],
      time: "12:00 PM",
      endTime: "",
      color: "#d99b43",
      description: "Syllabus and course details can be added when available.",
      standingNote: "Class schedule provided; syllabus details are still pending.",
    },
    {
      id: "torts",
      name: "Torts I",
      code: "Course details pending",
      section: "",
      professor: "Not yet provided",
      room: "Not yet provided",
      days: [1, 3, 5],
      time: "1:00 PM",
      endTime: "",
      color: "#5597c3",
      description: "Syllabus and course details can be added when available.",
      standingNote: "Class schedule provided; syllabus details are still pending.",
    },
    {
      id: "civil-procedure",
      name: "Civil Procedure I",
      code: "Course 510",
      section: "4",
      professor: "Ana M. Otero",
      room: "Room 208",
      days: [1, 3, 5],
      time: "3:00 PM",
      endTime: "3:50 PM",
      color: "#da557d",
      description: "Pleadings, joinder, federal jurisdiction, personal jurisdiction, and venue.",
      standingNote: "Assigned cases will be allocated to specific students before class. Monitor Canvas, TWEN, and email for quizzes, exercises, and assignment windows announced during the semester.",
    },
  ];

  const propertyRows = [
    ["2026-08-17", "class", "Welcome; Introduction to Property Law", "No textbook pages listed."],
    ["2026-08-19", "reading", "What is Property? Right to Transfer; Discovery and Conquest", "Read pp. 24-46 before class."],
    ["2026-08-21", "reading", "Right to Exclude; Trespass", "Read pp. 46-63 before class."],
    ["2026-08-24", "reading", "Right to Use", "Read pp. 63-76 before class."],
    ["2026-08-26", "reading", "Nuisance", "Read pp. 63-76 and 741-756 before class. The source table has duplicated/blank cells around this entry; verify against any revised schedule.", true],
    ["2026-08-28", "reading", "Right to Destroy", "Read pp. 76-88 before class."],
    ["2026-08-31", "exercise", "Nuisance Hypotheticals", "No textbook pages listed."],
    ["2026-09-02", "reading", "Ownership of Real Property; Adverse Possession", "Read pp. 89-107 before class."],
    ["2026-09-04", "reading", "Adverse Possession", "Read pp. 107-126 before class."],
    ["2026-09-07", "no-class", "Labor Day - no class", "University holiday."],
    ["2026-09-09", "reading", "Airspace Rights; Subsurface Rights", "Read pp. 127-141 before class."],
    ["2026-09-11", "reading", "Estates and Future Interests; Fee Simple Absolute", "Read pp. 295-305 before class."],
    ["2026-09-14", "exercise", "Adverse Possession Hypotheticals", "No textbook pages listed."],
    ["2026-09-16", "reading", "Life Estate", "Read pp. 305-316 before class."],
    ["2026-09-18", "reading", "Life Estate 2", "Read pp. 305-316 before class."],
    ["2026-09-21", "exercise", "Present Estates Hypotheticals", "No textbook pages listed."],
    ["2026-09-23", "reading", "Fee Simple Defeasible", "Read pp. 319-321: Fee Simple Determinable and Fee Simple Subject to a Condition Subsequent."],
    ["2026-09-25", "reading", "Executory Limitation and Other Defeasible-Fee Issues", "Read pp. 321-333 before class."],
    ["2026-09-28", "exercise", "Fee Simple Defeasible Hypotheticals", "No textbook pages listed."],
    ["2026-09-30", "review", "Midterm Review", "No textbook pages listed."],
    ["2026-10-02", "review", "Midterm Review 2", "No textbook pages listed."],
    ["2026-10-08", "exam", "Property Midterm Examination", "9:00-11:00 AM · LSB 203"],
    ["2026-10-12", "reading", "Modern Future Interests", "Read pp. 333-337: interests retained by the transferor."],
    ["2026-10-14", "reading", "Future Interests Created in a Transferee; Remainders", "Read pp. 337-341 before class."],
    ["2026-10-16", "reading", "Remainders", "Read pp. 337-341 before class."],
    ["2026-10-19", "reading", "Executory Interests", "Read pp. 342-344 before class."],
    ["2026-10-21", "reading", "Rule Against Perpetuities", "Read pp. 350-361 before class."],
    ["2026-10-23", "reading", "Concurrent Ownership and Marital Property", "Read pp. 363-369 before class."],
    ["2026-10-26", "exercise", "Future Interests Hypotheticals", "No textbook pages listed."],
    ["2026-10-28", "reading", "Severance; Partition", "Read pp. 369-382 before class."],
    ["2026-10-30", "reading", "Cotenant Rights and Duties", "Read pp. 382-386 before class."],
    ["2026-11-02", "reading", "Marital Property; Defining Marital Property", "Read pp. 387-404 before class."],
    ["2026-11-04", "reading", "Unmarried Couples; Same-Sex Marriage", "Read pp. 404-417 before class."],
    ["2026-11-06", "reading", "Water Law", "Read pp. 142-151 before class."],
    ["2026-11-09", "exercise", "Concurrent Ownership Hypotheticals", "No textbook pages listed."],
    ["2026-11-11", "reading", "Owning Personal Property; Rule of Capture", "Read pp. 153-165 before class."],
    ["2026-11-13", "reading", "Finders", "Read pp. 165-184 before class."],
    ["2026-11-16", "reading", "Adverse Possession of Chattels", "Read pp. 185-197 before class."],
    ["2026-11-18", "reading", "Gifts", "Read pp. 197-215 before class."],
    ["2026-11-20", "review", "Final Exam Review", "No textbook pages listed."],
    ["2026-11-23", "exam", "Property Final Examination", "Course-specific date conflicts with the university final-examination period beginning Nov. 30. Confirm if the professor updates it.", true],
    ["2026-11-24", "administrative", "Last day of classes", "Fall 2026 academic calendar."],
    ["2026-11-30", "administrative", "University final-examination period begins", "Runs through Dec. 10; conflicts with the Property final listed Nov. 23.", true],
    ["2026-08-19", "administrative", "Last day to add/drop", "Fall 2026 academic calendar."],
    ["2026-11-06", "administrative", "Last day to drop a class or withdraw", "Fall 2026 academic calendar."],
  ];

  const civilRows = [
    ["2026-08-14", "preparation", "Complete Civil Procedure pre-start review", "Before Aug. 17: watch the American Court System and Civil Litigation videos; read Orin Kerr's “How to Read a Legal Opinion”; complete Review Exercise #1. The syllabus labels this work “Pre-Start (August 10-14).”"],
    ["2026-08-17", "reading", "Introduction to Pleading", "For Aug. 17 and 19: review Exercise #1 and Chapters 1-2; review Chapter 13, pp. 405-452; review Exercise #2; prepare Ashcroft v. Iqbal (p. 430) and Swanson v. Citibank (p. 441). Exact division between the two class dates is not specified.", true, "2026-08-19"],
    ["2026-08-21", "reading", "Responding to the Complaint", "Chapter 14, pp. 453-465; answer Exercise #3 using the applicable rules; prepare Virgin Records America v. Lacey (p. 455)."],
    ["2026-08-24", "reading", "Pleading, continued", "For Aug. 24 and 26: Chapter 14, pp. 465-489; prepare Matos v. Nextran, Inc. (p. 465), Hunter v. Serv-Tech, Inc. (p. 475), and Reis Robotics USA, Inc. v. Concept Industries, Inc. (p. 483). Exact division between dates is not specified.", true, "2026-08-26"],
    ["2026-08-28", "reading", "Complete Chapter 14 reading", "Chapter 14, pp. 490-497; prepare Ingraham v. United States (listed at p. 489)."],
    ["2026-08-31", "exercise", "Complete Chapter 14 and Exercise #4", "Review the applicable rules and prepare answers before discussing the assigned Chapter 15 cases."],
    ["2026-09-02", "reading", "Care and Candor in Pleading", "For Sept. 2 and 4: Chapter 15, pp. 499-523; prepare Hays v. Sony Corp. of America (p. 501) and Hunter v. Earthgrains Co. Bakery (printed as p. 5112, likely a page-number typo).", true, "2026-09-04"],
    ["2026-09-07", "no-class", "Labor Day - no class", "University holiday."],
    ["2026-09-09", "reading", "Amending Pleadings", "Chapter 16, pp. 525-539; complete Exercise #5 questions on Rule 15; prepare Beeck v. Aquaslide ‘N’ Dive Corp. (p. 531)."],
    ["2026-09-11", "reading", "Joinder of Claims and Parties", "Review the Joinder of Parties PPT and Constitutional Requirement of Notice and Methods of Service PPT; prepare Mullane v. Central Hanover Bank (p. 320)."],
    ["2026-09-14", "reading", "Diversity Jurisdiction", "For Sept. 14 and 16: review the Diversity Jurisdiction PPT; begin Chapter 3, pp. 43-92; prepare Gordon v. Steele (p. 46) and Mas v. Perry (p. 56). Exact division between dates is not specified.", true, "2026-09-16"],
    ["2026-09-18", "reading", "Diversity Jurisdiction cases", "Prepare Hertz Corp. v. Friend (p. 66) and Diefenthal v. C.A.B. (p. 77)."],
    ["2026-09-21", "reading", "Federal Question Jurisdiction", "For Sept. 21 and 23: review the Federal Question Jurisdiction PPT; begin Chapter 4, pp. 93-127; prepare Louisville & Nashville RR v. Mottley (p. 96) and Gunn v. Minton (p. 113). Exact division between dates is not specified.", true, "2026-09-23"],
    ["2026-09-25", "reading", "Removal of Cases to Federal Court", "Review the Removal PPT; Chapter 5, pp. 129-145; prepare Avitts v. Amoco (p. 131)."],
    ["2026-09-28", "reading", "Removal and Supplemental Jurisdiction", "For Sept. 28 and 30: finalize removal; review the Supplemental Jurisdiction PPT; Chapter 20, pp. 671-705; prepare United Mine Workers v. Gibbs (p. 673). Exact division between dates is not specified.", true, "2026-09-30"],
    ["2026-10-02", "reading", "Finalize Supplemental Jurisdiction", "Prepare Owen Equipment & Erection v. Kroger (p. 685) and finalize the supplemental-jurisdiction discussion."],
    ["2026-10-05", "review", "Civil Procedure midterm week begins", "Midterm week runs Oct. 5-9."],
    ["2026-10-06", "exam", "Civil Procedure Midterm Exam", "Closed book · multiple-choice and essay questions · 9:00-11:00 AM."],
    ["2026-10-12", "reading", "Introduction to Personal Jurisdiction", "For Oct. 12 and 14: overview of Personal Jurisdiction; Chapter 6, pp. 149-180. Exact division between dates is not specified.", true, "2026-10-14"],
    ["2026-10-16", "reading", "Personal Jurisdiction cases", "Prepare Pennoyer v. Neff (p. 152) and International Shoe v. State of Washington (p. 167)."],
    ["2026-10-19", "reading", "Specific In Personam Jurisdiction", "For Oct. 19, 21, and 23: Chapter 7, pp. 181-254; prepare World Wide Volkswagen v. Woodson, Burger King v. Rudzewicz, Asahi Metal Industry v. Superior Court, and Ford Motor Co. v. Montana Eighth Judicial District Court. Exact division between dates is not specified.", true, "2026-10-23"],
    ["2026-10-26", "reading", "Other Constitutional Bases for Personal Jurisdiction", "For Oct. 26, 28, and 30: Chapter 8, pp. 255-297; prepare Daimler AG v. Bauman (p. 259) and Burnham v. Superior Court (p. 279). Exact division between dates is not specified.", true, "2026-10-30"],
    ["2026-11-02", "reading", "Long Arm Statutes", "For Nov. 2 and 4: Chapter 9, pp. 299-315; prepare Bensusan Restaurant Corp. v. King (p. 307). Exact division between dates is not specified.", true, "2026-11-04"],
    ["2026-11-06", "exercise", "Personal-jurisdiction writing exercises", "Writing exercises on personal jurisdiction."],
    ["2026-11-09", "reading", "Venue", "For Nov. 9, 11, and 13: review the Venue PPT; Chapter 11, pp. 355-371; prepare Uffner v. La Reunion Francaise (p. 364). Exact division between dates is not specified.", true, "2026-11-13"],
    ["2026-11-16", "reading", "Challenges to Venue", "For Nov. 16, 18, and 20: Chapter 12, pp. 373-400; prepare MacMunn v. Eli Lilly Co. (p. 377) and Piper Aircraft Company v. Reyno (p. 385). Exact division between dates is not specified.", true, "2026-11-20"],
    ["2026-11-23", "exam", "Civil Procedure Final Exam", "Cumulative and closed book; may include a take-home essay component. Time is not listed. The course date precedes the university's general final-examination period, so preserve both dates.", true],
    ["2026-11-24", "administrative", "Last day of class", "Listed the day after the course final examination."],
    ["2026-11-30", "administrative", "University final-examination period begins", "Runs through Dec. 10; the Civil Procedure course final is listed separately on Nov. 23.", true],
  ];

  function rowsToItems(courseId, rows) {
    return rows.map(([date, type, title, details, flagged = false, endDate = ""], index) => ({
      id: `${courseId}-${String(index + 1).padStart(2, "0")}`,
      courseId,
      date,
      endDate,
      type,
      title,
      details,
      flagged,
      done: false,
    }));
  }

  const materials = [
    {
      id: "property-summary",
      courseId: "property",
      title: "Property - LAW 506 Sec. 4: Docket Notes and Items to Confirm",
      type: "Verified syllabus notes",
      addedDate: "2026-08-12",
      content: "Recurring case-brief requirement, final-exam conflict, undated Theories of Property and Fee Tail readings, and take-home work whose dates will be announced later.",
    },
    {
      id: "civil-procedure-summary",
      courseId: "civil-procedure",
      title: "Civil Procedure I - Course 510 Sec. 4: Verified Syllabus Notes",
      type: "Verified syllabus notes",
      addedDate: "2026-08-13",
      content: "Professor Ana M. Otero. Monday, Wednesday, and Friday, 3:00-3:50 PM in Room 208. Includes pre-start work, weekly readings, Oct. 6 midterm, Nov. 23 final, and standing reminders for TWEN quizzes, timed essays, and assigned-case notices.",
    },
  ];

  window.KITAS_DOCKET_SEED = {
    term: { name: "Fall 2026", startDate: "2026-08-17", endDate: "2026-11-24" },
    courses,
    items: [...rowsToItems("property", propertyRows), ...rowsToItems("civil-procedure", civilRows)],
    materials,
    standingFlags: [
      { id: "property-undated-theories", courseId: "property", title: "Theories of Property has no date", details: "Pages 1-24 appear without a clearly printed ‘Before This Date.’" },
      { id: "property-undated-fee-tail", courseId: "property", title: "Fee Tail has no date", details: "Pages 317-319 appear without a clearly printed ‘Before This Date.’" },
      { id: "property-comprehensive", courseId: "property", title: "Comprehensive Examination is TBA", details: "No date, time, or location is provided." },
      { id: "property-take-home", courseId: "property", title: "Property take-home work will be announced", details: "Several problems and hypotheticals are expected, but the syllabus gives no advance dates." },
      { id: "civil-twen", courseId: "civil-procedure", title: "Mandatory TWEN quizzes will be announced", details: "Watch email for each quiz's open and close dates." },
      { id: "civil-essays", courseId: "civil-procedure", title: "Timed essay-exam dates are pending", details: "Multiple graded essays are planned; dates and point values will be announced." },
      { id: "civil-uniform", courseId: "civil-procedure", title: "Uniform Exam date is not listed", details: "The syllabus says it will be administered in December and counts for 50% of the final grade." },
      { id: "civil-cases", courseId: "civil-procedure", title: "Individual case assignments are pending", details: "The professor will assign cases to specific students before class and post a separate document with focus questions." },
    ],
  };
})();
