(function () {
  const courses = [
    {
      id: "property",
      name: "Property I",
      code: "LAW 506",
      section: "4",
      professor: "Emeka Duruigbo",
      room: "LSB 208",
      days: [1, 3, 5],
      time: "9:00 AM",
      endTime: "9:50 AM",
      color: "#74a963",
      description: "Property rights, estates, future interests, ownership, and personal property.",
      standingNote: "Before each class, submit a one-page case brief for one case from that day's assigned reading to propertycasebriefs@gmail.com. No brief is required when the reading contains no case.",
    },
    {
      id: "contracts",
      name: "Contracts I",
      code: "Course details pending",
      section: "",
      professor: "Not yet provided",
      room: "Not yet provided",
      days: [1, 3, 5],
      time: "11:00 AM",
      endTime: "",
      color: "#9255cb",
      description: "Syllabus and course details can be added when available.",
      standingNote: "Class schedule provided; syllabus details are still pending.",
    },
    {
      id: "legal-analysis",
      name: "Legal Analysis",
      code: "Course No. 7310",
      section: "1",
      professor: "Jenifer Points",
      email: "jenifer.points@tmslaw.tsu.edu",
      phone: "713-313-7276",
      officeLocation: "Room 231E",
      officeHours: "Mondays and Wednesdays, 1:00-3:00 PM; other times by appointment in person or through Zoom.",
      room: "Room 107",
      days: [1, 3, 5],
      time: "12:00 PM",
      endTime: "12:50 PM",
      color: "#d99b43",
      description: "Critical reading, rule development, legal analysis, and predictive memorandum skills.",
      standingNote: "Canvas is used for course materials, grades, email, and submissions. Most assignments receive no credit if late; save every Canvas confirmation email.",
      alert: "NO GENERATIVE AI: Professor Points prohibits ChatGPT and every tool that generates, writes, or rewrites text for this course. Kita's Docket may track dates and requirements only; do not use it to create or complete Legal Analysis coursework.",
      aiRestricted: true,
      requiredMaterials: [
        "Coughlin, Malmud & Patrick, A Lawyer Writes, 4th ed.",
        "Brett A. Brosseit et al., Applied Critical Thinking & Analysis",
        "Romantz & Vinson, Legal Analysis, 4th ed.",
        "Digital Course Reader (320 pages)",
        "Core Grammar for Lawyers online program",
      ],
      grading: [
        "Daily exercises and other assignments - 100 points (10%)",
        "Exam 1 - 100 points (10%)",
        "Midterm Exam - 250 points (25%)",
        "Predictive Memorandum - 100 points (10%)",
        "Final Exam - 350 points (35% per grading table; a later policy paragraph says 30% - confirm)",
        "Core Grammar for Lawyers - 50 points (5%)",
        "Participation, Professionalism, and Attendance - 50 points (5%)",
      ],
      rules: [
        "Attendance is mandatory; only three absences are permitted.",
        "Most assignments must be uploaded to Canvas; no credit is given for late work.",
        "Use Word unless told otherwise; 14-point professional font, one-inch margins, double-spaced text, and bottom-centered page numbers.",
        "Remove identifying metadata and use an anonymous exam number when instructed.",
        "Collaboration is allowed only when Professor Points expressly permits it; final written work must be Rekita's own.",
      ],
    },
    {
      id: "torts",
      name: "Torts I",
      code: "LAW 508",
      section: "4",
      professor: "L. Darnell Weeden",
      email: "Larry.Weeden@tmslaw.tsu.edu",
      phone: "713-313-4249",
      officeLocation: "TMSL 236L",
      officeHours: "As printed: Mon./Tue./Wed./Fri. 9:00-9:50 AM; Mon./Wed./Fri. 11:00 AM-12:50 PM and 2:00-2:10 PM.",
      room: "Room 206",
      days: [1, 3, 5],
      time: "1:00 PM",
      endTime: "1:50 PM",
      color: "#5597c3",
      description: "Intentional torts, privileges, negligence, causation, multiple tortfeasors, duty of care, and landowner liability.",
      standingNote: "Join the course TWEN page and monitor it for materials and announcements. Read assigned materials before discussion, including notes following cases.",
      requiredMaterials: [
        "Prosser, Wade & Schwartz's Torts, Cases and Materials, 15th ed. (2024)",
        "ISBN 9798887865522",
        "Highly recommended: Statsky & Wernet, Case Analysis and Fundamentals of Legal Writing (any edition)",
      ],
      grading: [
        "Exam #1 - 12.5%",
        "Midterm Exam (Exam #2) - 25%",
        "Exam #3 - 12.5%",
        "TMSL Final Uniform/Comprehensive Examination - 50%",
      ],
      rules: [
        "Five absences are permitted; excess absences may lower the grade or cause administrative withdrawal.",
        "All three course exams and the final uniform examination are mandatory.",
        "Class participation is expected but earns no points; some cases may be assigned to individual students.",
        "Devices may be used only for the e-textbook, notes, and class-related reference; mute phones and smart watches.",
      ],
    },
    {
      id: "civil-procedure",
      name: "Civil Procedure I",
      code: "Course 510",
      section: "4",
      professor: "Ana M. Otero",
      room: "Room 208",
      days: [1, 3, 5],
      time: "3:00 PM",
      endTime: "3:50 PM",
      color: "#da557d",
      description: "Pleadings, joinder, federal jurisdiction, personal jurisdiction, and venue.",
      standingNote: "Assigned cases will be allocated to specific students before class. Monitor Canvas, TWEN, and email for quizzes, exercises, and assignment windows announced during the semester.",
    },
  ];

  const propertyRows = [
    ["2026-08-17", "class", "Welcome; Introduction to Property Law", "No textbook pages listed."],
    ["2026-08-19", "reading", "What is Property? Right to Transfer; Discovery and Conquest", "Read pp. 24-46 before class."],
    ["2026-08-21", "reading", "Right to Exclude; Trespass", "Read pp. 46-63 before class."],
    ["2026-08-24", "reading", "Right to Use", "Read pp. 63-76 before class."],
    ["2026-08-26", "reading", "Nuisance", "Read pp. 63-76 and 741-756 before class. The source table has duplicated/blank cells around this entry; verify against any revised schedule.", true],
    ["2026-08-28", "reading", "Right to Destroy", "Read pp. 76-88 before class."],
    ["2026-08-31", "exercise", "Nuisance Hypotheticals", "No textbook pages listed."],
    ["2026-09-02", "reading", "Ownership of Real Property; Adverse Possession", "Read pp. 89-107 before class."],
    ["2026-09-04", "reading", "Adverse Possession", "Read pp. 107-126 before class."],
    ["2026-09-07", "no-class", "Labor Day - no class", "University holiday."],
    ["2026-09-09", "reading", "Airspace Rights; Subsurface Rights", "Read pp. 127-141 before class."],
    ["2026-09-11", "reading", "Estates and Future Interests; Fee Simple Absolute", "Read pp. 295-305 before class."],
    ["2026-09-14", "exercise", "Adverse Possession Hypotheticals", "No textbook pages listed."],
    ["2026-09-16", "reading", "Life Estate", "Read pp. 305-316 before class."],
    ["2026-09-18", "reading", "Life Estate 2", "Read pp. 305-316 before class."],
    ["2026-09-21", "exercise", "Present Estates Hypotheticals", "No textbook pages listed."],
    ["2026-09-23", "reading", "Fee Simple Defeasible", "Read pp. 319-321: Fee Simple Determinable and Fee Simple Subject to a Condition Subsequent."],
    ["2026-09-25", "reading", "Executory Limitation and Other Defeasible-Fee Issues", "Read pp. 321-333 before class."],
    ["2026-09-28", "exercise", "Fee Simple Defeasible Hypotheticals", "No textbook pages listed."],
    ["2026-09-30", "review", "Midterm Review", "No textbook pages listed."],
    ["2026-10-02", "review", "Midterm Review 2", "No textbook pages listed."],
    ["2026-10-08", "exam", "Property Midterm Examination", "9:00-11:00 AM · LSB 203"],
    ["2026-10-12", "reading", "Modern Future Interests", "Read pp. 333-337: interests retained by the transferor."],
    ["2026-10-14", "reading", "Future Interests Created in a Transferee; Remainders", "Read pp. 337-341 before class."],
    ["2026-10-16", "reading", "Remainders", "Read pp. 337-341 before class."],
    ["2026-10-19", "reading", "Executory Interests", "Read pp. 342-344 before class."],
    ["2026-10-21", "reading", "Rule Against Perpetuities", "Read pp. 350-361 before class."],
    ["2026-10-23", "reading", "Concurrent Ownership and Marital Property", "Read pp. 363-369 before class."],
    ["2026-10-26", "exercise", "Future Interests Hypotheticals", "No textbook pages listed."],
    ["2026-10-28", "reading", "Severance; Partition", "Read pp. 369-382 before class."],
    ["2026-10-30", "reading", "Cotenant Rights and Duties", "Read pp. 382-386 before class."],
    ["2026-11-02", "reading", "Marital Property; Defining Marital Property", "Read pp. 387-404 before class."],
    ["2026-11-04", "reading", "Unmarried Couples; Same-Sex Marriage", "Read pp. 404-417 before class."],
    ["2026-11-06", "reading", "Water Law", "Read pp. 142-151 before class."],
    ["2026-11-09", "exercise", "Concurrent Ownership Hypotheticals", "No textbook pages listed."],
    ["2026-11-11", "reading", "Owning Personal Property; Rule of Capture", "Read pp. 153-165 before class."],
    ["2026-11-13", "reading", "Finders", "Read pp. 165-184 before class."],
    ["2026-11-16", "reading", "Adverse Possession of Chattels", "Read pp. 185-197 before class."],
    ["2026-11-18", "reading", "Gifts", "Read pp. 197-215 before class."],
    ["2026-11-20", "review", "Final Exam Review", "No textbook pages listed."],
    ["2026-11-23", "exam", "Property Final Examination", "Course-specific date conflicts with the university final-examination period beginning Nov. 30. Confirm if the professor updates it.", true],
    ["2026-11-24", "administrative", "Last day of classes", "Fall 2026 academic calendar."],
    ["2026-11-30", "administrative", "University final-examination period begins", "Runs through Dec. 10; conflicts with the Property final listed Nov. 23.", true],
    ["2026-08-19", "administrative", "Last day to add/drop", "Fall 2026 academic calendar."],
    ["2026-11-06", "administrative", "Last day to drop a class or withdraw", "Fall 2026 academic calendar."],
  ];

  const legalAnalysisRows = [
    ["2026-08-17", "reading", "Week 1 - Introduction; Sources and Systems of Law", "A Lawyer Writes pp. 15-31; Legal Analysis pp. 3-19; ACTLA pp. 3-23; Course Reader pp. 3-10, 36-58, 98-110, 250-264. Topics include jurisdiction, precedent, authority, case structure, and litigation.", false, "2026-08-21"],
    ["2026-08-24", "assignment", "Eilers v. Coy case brief due", "Post on Canvas before class starts. Brief Eilers v. Coy, 582 F. Supp. 1093 (D. Minn. 1984), using Course Reader pp. 80-82 and briefing guidance at pp. 13-17."],
    ["2026-08-24", "reading", "Week 2 - Critical Reading and Case Briefing", "A Lawyer Writes pp. 33-64; Course Reader pp. 16-18, 59-78; ACTLA pp. 27-58. Includes issue statements and broad versus narrow issues.", false, "2026-08-28"],
    ["2026-08-31", "assignment", "First three attractive-nuisance case briefs due", "Post on Canvas before class starts. Complete briefs for the first three cases in the Attractive Nuisance Memorandum assignment case pool."],
    ["2026-08-31", "reading", "Week 3 - Explicit and Implicit Rules", "Legal Analysis pp. 21-29, 31-34; A Lawyer Writes pp. 65-78, 105-114; ACTLA pp. 59-67, 127-133, 152-167; Course Reader pp. 80-93. The syllabus says the ACTLA cases do not need briefs.", false, "2026-09-04"],
    ["2026-09-09", "assignment", "Implicit-rules homework due", "Post on Canvas before class starts and bring a printed copy. From ACTLA pp. 152-156, write every implicit rule identified from the courts' holdings."],
    ["2026-09-09", "reading", "Week 4 - Rule Synthesis and Inductive Reasoning", "ACTLA pp. 133-135, 193-212; Legal Analysis pp. 30-31, 47-50; Course Reader pp. 23-34, 237-240. Monday is a holiday, so class meets Wednesday and Friday.", false, "2026-09-11"],
    ["2026-09-14", "reading", "Week 5 - Clear Rule Statements and Rule Explanation", "A Lawyer Writes pp. 115-118; ACTLA pp. 67-78. Exam #1 is Friday.", false, "2026-09-18"],
    ["2026-09-18", "exam", "Legal Analysis Exam #1", "Multiple-choice and short-answer exam covering case reading, rule types, explicit and implicit rules, synthesis, rule ordering, court structure, judicial opinions, and case briefing."],
    ["2026-09-21", "reading", "Week 6 - Deductive Analysis; CRAC/CREAC/IRAC", "A Lawyer Writes pp. 99-103; Legal Analysis pp. 67-84; ACTLA pp. 96-122, 139-150; Course Reader pp. 151-185. Includes essay-exam writing skills.", false, "2026-09-25"],
    ["2026-09-28", "assignment", "Bubbles practice essay due", "Post the completed practice-exam essay on Canvas by 9:00 AM."],
    ["2026-09-28", "reading", "Week 7 - Live Drafting and Memorandum Basics", "Legal Analysis pp. 119-144; Attractive Nuisance Memorandum Assignment on Canvas; A Lawyer Writes pp. 3-9; Course Reader pp. 282-298. Includes live review and CREAC discussion-section basics.", false, "2026-10-02"],
    ["2026-10-05", "no-class", "Legal Analysis midterm week - no class", "No regular class during midterm week.", false, "2026-10-09"],
    ["2026-10-07", "exam", "Legal Analysis Midterm Exam", "9:00 AM - Room 202. NextGen integrated-set format."],
    ["2026-10-12", "assignment", "Attractive-nuisance case briefs due", "Post on Canvas before class starts. Brief Lopez-Perez v. BNSF Railway Co., Renaud v. Black, and Craig v. Bailey Bros. Realty, Inc. using only the edited cases on Canvas and the UDW approach."],
    ["2026-10-12", "reading", "Week 9 - CREAC Application; Counterargument and Rebuttal", "A Lawyer Writes pp. 155-161, 181-195; ACTLA pp. 79-94, 169-176. Includes review of the Micki Mouse CREAC.", false, "2026-10-16"],
    ["2026-10-16", "assignment", "Micki Mouse CREAC due", "Post on Canvas by 9:00 AM."],
    ["2026-10-19", "reading", "Week 10 - Completing and Polishing the Memorandum", "A Lawyer Writes pp. 141-154, 251-283, 286-292 through section b, and pp. 295-309 starting at section B; Course Reader pp. 301-322. Covers remaining memo parts, citation, editing, and polishing.", false, "2026-10-23"],
    ["2026-10-25", "assignment", "Attractive Nuisance Memorandum due", "Submit on Canvas by 11:59 PM using an anonymous exam number. Bring a printed copy showing only the exam number to Monday's class."],
    ["2026-10-26", "reading", "Week 11 - Rule Synthesis and Statutory Interpretation", "More Rule Synthesis reading is TBD. Also read Legal Analysis pp. 85-99; A Lawyer Writes pp. 215-231; Course Reader pp. 111-131, 224-236, 243-249, 260-266. Bring a printed memorandum.", true, "2026-10-30"],
    ["2026-11-02", "reading", "Week 12 - Analogical Reasoning", "A Lawyer Writes pp. 163-164; Legal Analysis pp. 39-65; ACTLA pp. 135-137; Course Reader pp. 94-96, 132-140, 267-269; People v. Barney, 742 N.Y.S.2d 451, via Lexis or Westlaw.", false, "2026-11-06"],
    ["2026-11-08", "assignment", "Core Grammar for Lawyers due", "Complete all 24 lessons and earn at least 75% on the post-test by 11:59 PM. Worth 50 points; late work or a score below 75 earns zero. A 95+ post-test score earns 10 extra-credit points."],
    ["2026-11-09", "reading", "Week 13 - Policy-Based Reasoning and Bases for Rules", "ACTLA pp. 187-188; Legal Analysis pp. 101-117; A Lawyer Writes pp. 207-214; Course Reader pp. 195-213.", false, "2026-11-13"],
    ["2026-11-16", "reading", "Week 14 - Review of Rules and Legal Analysis", "Course Reader pp. 214-223; final-exam review.", false, "2026-11-20"],
    ["2026-11-23", "review", "Week 15 - Final Exam Review", "Reading is TBD. Final exam date remains TBD.", true],
  ];

  const tortsRows = [
    ["2026-08-17", "reading", "Week 1 - Introduction, Fault, Procedure, Intent, and Battery", "Read pp. 1-53.", false, "2026-08-21"],
    ["2026-08-24", "reading", "Week 2 - Intentional Interference with Person or Property", "Read pp. 53-107: battery, assault, false imprisonment, intentional infliction of emotional distress, trespass to land, and trespass to chattels.", false, "2026-08-28"],
    ["2026-08-31", "reading", "Week 3 - Conversion, Participation Liability, Privileges, and Consent", "Read pp. 107-157.", false, "2026-09-04"],
    ["2026-09-07", "reading", "Week 4 - Privileges and Defenses", "Read pp. 157-192: consent, self-defense, defense and recovery of property, shopkeeper's privilege, necessity, authority of law, and discipline. No class Monday for Labor Day.", false, "2026-09-11"],
    ["2026-09-14", "reading", "Week 5 - Negligence, Breach, and the Reasonable Person", "Read pp. 193-227. Exam #1 is Friday.", false, "2026-09-18"],
    ["2026-09-18", "exam", "Torts Exam #1", "12.5% of final grade. Includes 25 objective multiple-choice questions and a five-point timed essay."],
    ["2026-09-21", "reading", "Week 6 - Professional Standard and Aggravated Negligence", "Read pp. 227-277: reasonable person, professional standard, urgent care, gross negligence, recklessness, and who decides rules of conduct.", false, "2026-09-25"],
    ["2026-09-28", "reading", "Week 7 - Rules of Conduct and Statutory Violations", "Read pp. 277-330: judge versus jury and violation of statute as proof of negligence.", false, "2026-10-02"],
    ["2026-10-05", "review", "Week 8 - Torts midterm week", "Midterm exam week runs Monday through Friday.", false, "2026-10-09"],
    ["2026-10-09", "exam", "Torts Midterm Exam (Exam #2)", "9:00-11:00 AM - Room 202. Counts for 25% and consists of 60 objective multiple-choice questions."],
    ["2026-10-12", "reading", "Week 9 - Proof of Negligence and Causation in Fact", "Read pp. 330-384: but-for test, reasonable inference, concurrent and overdetermined causes, substantial factor, loss of chance, toxic torts, and epidemiologic evidence.", false, "2026-10-16"],
    ["2026-10-19", "reading", "Week 10 - Causation and Scope of Liability", "Read pp. 384-433: toxic tort evidence, proximate/legal cause, direct versus remote causes, foreseeability, increased risk, and proportionality.", false, "2026-10-23"],
    ["2026-10-26", "reading", "Week 11 - Intervening Causes and Multiple Tortfeasors", "Read pp. 434-489: scope of liability, intervening causes, joinder, satisfaction and release, contribution, and indemnity.", false, "2026-10-30"],
    ["2026-11-02", "reading", "Week 12 - Apportionment and Duty of Care", "Read pp. 489-540: multiple tortfeasors, contribution and indemnity, apportionment, privity, tort versus contract, foreseeability limits, policy-based no-duty rules, and failure to act.", false, "2026-11-06"],
    ["2026-11-09", "reading", "Week 13 - Failure to Act, Economic Loss, and Emotional Distress", "Read pp. 540-598.", false, "2026-11-13"],
    ["2026-11-16", "reading", "Week 14 - Emotional Distress and Landowner Liability", "Read pp. 598-668: unborn children, owners and occupiers of land, and injuries on and outside the premises.", false, "2026-11-20"],
    ["2026-11-23", "exam", "Torts Exam #3", "12.5% of final grade. Consists of 30 objective multiple-choice questions."],
  ];

  const civilRows = [
    ["2026-08-14", "preparation", "Complete Civil Procedure pre-start review", "Before Aug. 17: watch the American Court System and Civil Litigation videos; read Orin Kerr's “How to Read a Legal Opinion”; complete Review Exercise #1. The syllabus labels this work “Pre-Start (August 10-14).”"],
    ["2026-08-17", "reading", "Introduction to Pleading", "For Aug. 17 and 19: review Exercise #1 and Chapters 1-2; review Chapter 13, pp. 405-452; review Exercise #2; prepare Ashcroft v. Iqbal (p. 430) and Swanson v. Citibank (p. 441). Exact division between the two class dates is not specified.", true, "2026-08-19"],
    ["2026-08-21", "reading", "Responding to the Complaint", "Chapter 14, pp. 453-465; answer Exercise #3 using the applicable rules; prepare Virgin Records America v. Lacey (p. 455)."],
    ["2026-08-24", "reading", "Pleading, continued", "For Aug. 24 and 26: Chapter 14, pp. 465-489; prepare Matos v. Nextran, Inc. (p. 465), Hunter v. Serv-Tech, Inc. (p. 475), and Reis Robotics USA, Inc. v. Concept Industries, Inc. (p. 483). Exact division between dates is not specified.", true, "2026-08-26"],
    ["2026-08-28", "reading", "Complete Chapter 14 reading", "Chapter 14, pp. 490-497; prepare Ingraham v. United States (listed at p. 489)."],
    ["2026-08-31", "exercise", "Complete Chapter 14 and Exercise #4", "Review the applicable rules and prepare answers before discussing the assigned Chapter 15 cases."],
    ["2026-09-02", "reading", "Care and Candor in Pleading", "For Sept. 2 and 4: Chapter 15, pp. 499-523; prepare Hays v. Sony Corp. of America (p. 501) and Hunter v. Earthgrains Co. Bakery (printed as p. 5112, likely a page-number typo).", true, "2026-09-04"],
    ["2026-09-07", "no-class", "Labor Day - no class", "University holiday."],
    ["2026-09-09", "reading", "Amending Pleadings", "Chapter 16, pp. 525-539; complete Exercise #5 questions on Rule 15; prepare Beeck v. Aquaslide ‘N’ Dive Corp. (p. 531)."],
    ["2026-09-11", "reading", "Joinder of Claims and Parties", "Review the Joinder of Parties PPT and Constitutional Requirement of Notice and Methods of Service PPT; prepare Mullane v. Central Hanover Bank (p. 320)."],
    ["2026-09-14", "reading", "Diversity Jurisdiction", "For Sept. 14 and 16: review the Diversity Jurisdiction PPT; begin Chapter 3, pp. 43-92; prepare Gordon v. Steele (p. 46) and Mas v. Perry (p. 56). Exact division between dates is not specified.", true, "2026-09-16"],
    ["2026-09-18", "reading", "Diversity Jurisdiction cases", "Prepare Hertz Corp. v. Friend (p. 66) and Diefenthal v. C.A.B. (p. 77)."],
    ["2026-09-21", "reading", "Federal Question Jurisdiction", "For Sept. 21 and 23: review the Federal Question Jurisdiction PPT; begin Chapter 4, pp. 93-127; prepare Louisville & Nashville RR v. Mottley (p. 96) and Gunn v. Minton (p. 113). Exact division between dates is not specified.", true, "2026-09-23"],
    ["2026-09-25", "reading", "Removal of Cases to Federal Court", "Review the Removal PPT; Chapter 5, pp. 129-145; prepare Avitts v. Amoco (p. 131)."],
    ["2026-09-28", "reading", "Removal and Supplemental Jurisdiction", "For Sept. 28 and 30: finalize removal; review the Supplemental Jurisdiction PPT; Chapter 20, pp. 671-705; prepare United Mine Workers v. Gibbs (p. 673). Exact division between dates is not specified.", true, "2026-09-30"],
    ["2026-10-02", "reading", "Finalize Supplemental Jurisdiction", "Prepare Owen Equipment & Erection v. Kroger (p. 685) and finalize the supplemental-jurisdiction discussion."],
    ["2026-10-05", "review", "Civil Procedure midterm week begins", "Midterm week runs Oct. 5-9."],
    ["2026-10-06", "exam", "Civil Procedure Midterm Exam", "Closed book · multiple-choice and essay questions · 9:00-11:00 AM."],
    ["2026-10-12", "reading", "Introduction to Personal Jurisdiction", "For Oct. 12 and 14: overview of Personal Jurisdiction; Chapter 6, pp. 149-180. Exact division between dates is not specified.", true, "2026-10-14"],
    ["2026-10-16", "reading", "Personal Jurisdiction cases", "Prepare Pennoyer v. Neff (p. 152) and International Shoe v. State of Washington (p. 167)."],
    ["2026-10-19", "reading", "Specific In Personam Jurisdiction", "For Oct. 19, 21, and 23: Chapter 7, pp. 181-254; prepare World Wide Volkswagen v. Woodson, Burger King v. Rudzewicz, Asahi Metal Industry v. Superior Court, and Ford Motor Co. v. Montana Eighth Judicial District Court. Exact division between dates is not specified.", true, "2026-10-23"],
    ["2026-10-26", "reading", "Other Constitutional Bases for Personal Jurisdiction", "For Oct. 26, 28, and 30: Chapter 8, pp. 255-297; prepare Daimler AG v. Bauman (p. 259) and Burnham v. Superior Court (p. 279). Exact division between dates is not specified.", true, "2026-10-30"],
    ["2026-11-02", "reading", "Long Arm Statutes", "For Nov. 2 and 4: Chapter 9, pp. 299-315; prepare Bensusan Restaurant Corp. v. King (p. 307). Exact division between dates is not specified.", true, "2026-11-04"],
    ["2026-11-06", "exercise", "Personal-jurisdiction writing exercises", "Writing exercises on personal jurisdiction."],
    ["2026-11-09", "reading", "Venue", "For Nov. 9, 11, and 13: review the Venue PPT; Chapter 11, pp. 355-371; prepare Uffner v. La Reunion Francaise (p. 364). Exact division between dates is not specified.", true, "2026-11-13"],
    ["2026-11-16", "reading", "Challenges to Venue", "For Nov. 16, 18, and 20: Chapter 12, pp. 373-400; prepare MacMunn v. Eli Lilly Co. (p. 377) and Piper Aircraft Company v. Reyno (p. 385). Exact division between dates is not specified.", true, "2026-11-20"],
    ["2026-11-23", "exam", "Civil Procedure Final Exam", "Cumulative and closed book; may include a take-home essay component. Time is not listed. The course date precedes the university's general final-examination period, so preserve both dates.", true],
    ["2026-11-24", "administrative", "Last day of class", "Listed the day after the course final examination."],
    ["2026-11-30", "administrative", "University final-examination period begins", "Runs through Dec. 10; the Civil Procedure course final is listed separately on Nov. 23.", true],
  ];

  function rowsToItems(courseId, rows) {
    return rows.map(([date, type, title, details, flagged = false, endDate = ""], index) => ({
      id: `${courseId}-${String(index + 1).padStart(2, "0")}`,
      courseId,
      date,
      endDate,
      type,
      title,
      details,
      flagged,
      done: false,
    }));
  }

  const materials = [
    {
      id: "property-summary",
      courseId: "property",
      title: "Property - LAW 506 Sec. 4: Docket Notes and Items to Confirm",
      type: "Verified syllabus notes",
      addedDate: "2026-08-12",
      content: "Recurring case-brief requirement, final-exam conflict, undated Theories of Property and Fee Tail readings, and take-home work whose dates will be announced later.",
    },
    {
      id: "civil-procedure-summary",
      courseId: "civil-procedure",
      title: "Civil Procedure I - Course 510 Sec. 4: Verified Syllabus Notes",
      type: "Verified syllabus notes",
      addedDate: "2026-08-13",
      content: "Professor Ana M. Otero. Monday, Wednesday, and Friday, 3:00-3:50 PM in Room 208. Includes pre-start work, weekly readings, Oct. 6 midterm, Nov. 23 final, and standing reminders for TWEN quizzes, timed essays, and assigned-case notices.",
    },
    {
      id: "legal-analysis-summary",
      courseId: "legal-analysis",
      title: "Legal Analysis - Course No. 7310 Sec. 1: Verified Syllabus Notes",
      type: "Verified Fall 2026 syllabus",
      addedDate: "2026-08-16",
      content: "Professor Jenifer Points. M/W/F, 12:00-12:50 PM in Room 107. Includes required books, weekly readings, all dated Canvas work, exams, memorandum, Core Grammar, grading, three-absence limit, formatting rules, and the strict prohibition on generative AI.",
    },
    {
      id: "torts-summary",
      courseId: "torts",
      title: "Torts I - LAW 508 Sec. 4: Verified Syllabus Notes",
      type: "Verified Fall 2026 syllabus",
      addedDate: "2026-08-16",
      content: "Professor L. Darnell Weeden. M/W/F, 1:00-1:50 PM in Room 206. Includes the required 15th-edition casebook, TWEN reminder, complete weekly readings, three mandatory course exams, final exam TBD, grading weights, and five-absence limit.",
    },
  ];

  window.KITAS_DOCKET_SEED = {
    term: { name: "Fall 2026", startDate: "2026-08-17", endDate: "2026-11-24" },
    courses,
    items: [
      ...rowsToItems("property", propertyRows),
      ...rowsToItems("legal-analysis", legalAnalysisRows),
      ...rowsToItems("torts", tortsRows),
      ...rowsToItems("civil-procedure", civilRows),
    ],
    materials,
    standingFlags: [
      { id: "property-undated-theories", courseId: "property", title: "Theories of Property has no date", details: "Pages 1-24 appear without a clearly printed ‘Before This Date.’" },
      { id: "property-undated-fee-tail", courseId: "property", title: "Fee Tail has no date", details: "Pages 317-319 appear without a clearly printed ‘Before This Date.’" },
      { id: "property-comprehensive", courseId: "property", title: "Comprehensive Examination is TBA", details: "No date, time, or location is provided." },
      { id: "property-take-home", courseId: "property", title: "Property take-home work will be announced", details: "Several problems and hypotheticals are expected, but the syllabus gives no advance dates." },
      { id: "civil-twen", courseId: "civil-procedure", title: "Mandatory TWEN quizzes will be announced", details: "Watch email for each quiz's open and close dates." },
      { id: "civil-essays", courseId: "civil-procedure", title: "Timed essay-exam dates are pending", details: "Multiple graded essays are planned; dates and point values will be announced." },
      { id: "civil-uniform", courseId: "civil-procedure", title: "Uniform Exam date is not listed", details: "The syllabus says it will be administered in December and counts for 50% of the final grade." },
      { id: "civil-cases", courseId: "civil-procedure", title: "Individual case assignments are pending", details: "The professor will assign cases to specific students before class and post a separate document with focus questions." },
      { id: "legal-ai-ban", courseId: "legal-analysis", title: "Generative AI is prohibited", details: "Do not use ChatGPT or any tool that generates, writes, or rewrites text for Legal Analysis. Use Kita's Docket only to track dates and course requirements." },
      { id: "legal-final-tbd", courseId: "legal-analysis", title: "Legal Analysis final exam date is TBD", details: "The syllabus provides the format and topics but no date, time, or room." },
      { id: "legal-final-weight-conflict", courseId: "legal-analysis", title: "Confirm Legal Analysis final-exam weight", details: "The grading table lists 350 of 1000 points (35%), while a later policy paragraph says 30%." },
      { id: "legal-week11-reading", courseId: "legal-analysis", title: "Week 11 More Rule Synthesis reading is TBD", details: "The syllabus lists the topic for Oct. 26-30 but leaves this reading as TBD." },
      { id: "legal-week15-reading", courseId: "legal-analysis", title: "Nov. 23 final-review reading is TBD", details: "The final-review topic is listed, but the assigned reading remains TBD." },
      { id: "legal-grammar-groups", courseId: "legal-analysis", title: "Confirm Rekita's grammar-presentation group", details: "Group dates: Sept. 9, 11, 21, 28, 30; Oct. 12, 14, 28; Nov. 2, 4, 11, 18. Add only Rekita's assigned date to her personal deadline list." },
      { id: "torts-final-tbd", courseId: "torts", title: "Torts final uniform examination is TBD", details: "TMSL Administration will announce the date during the Nov. 30-Dec. 10 final-exam period." },
      { id: "torts-office-hours", courseId: "torts", title: "Torts office-hours line should be confirmed", details: "The app preserves the unusually broad schedule exactly as printed in the syllabus." },
      { id: "torts-practice", courseId: "torts", title: "Additional Torts exams or reviews may be announced", details: "Monitor TWEN for separately scheduled reviews, practice exams, and other materials." },
    ],
  };
})();
